# Generated by Django 3.2.9 on 2021-12-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto_tracker',
            name='symbol',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock_tracker',
            name='symbol',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
