# Generated by Django 3.2 on 2021-12-09 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_dashboard', '0002_auto_20211207_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto_tracker',
            name='cost_per_share',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stock_tracker',
            name='cost_per_share',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
