# Generated by Django 3.2 on 2021-12-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_dashboard', '0003_auto_20211209_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto_tracker',
            name='asset',
            field=models.CharField(choices=[('BTC', 'BITCOIN'), ('L1', 'LAYER1'), ('L2', 'LAYER2'), ('Gaming', 'GAMING')], default='BTC', max_length=10),
        ),
        migrations.AlterField(
            model_name='crypto_tracker',
            name='long_or_short',
            field=models.CharField(choices=[('Long', 'LONG'), ('Short', 'SHORT')], default='Long', max_length=10),
        ),
        migrations.AlterField(
            model_name='stock_tracker',
            name='asset',
            field=models.CharField(choices=[('Equites', 'Equites'), ('Bbonds', 'Bonds'), ('Futures', 'Futures')], default='Equites', max_length=10),
        ),
        migrations.AlterField(
            model_name='stock_tracker',
            name='long_or_short',
            field=models.CharField(choices=[('Long', 'LONG'), ('Short', 'SHORT')], default='Long', max_length=10),
        ),
    ]
